name: CI

on: [push]

jobs:
  upload_progress_bar_to_wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki
    - run: |
        cd wiki
        printf '%s\n%s\n' "## Tests are running! Please wait!" "![](https://i.gifer.com/origin/82/82a1ed531e333926a8ca2a00c277e0d1.gif)" > Home.md
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit --allow-empty -m "Add progress bar"
        git push

  run_tests:
    needs: upload_progress_bar_to_wiki
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: niosus/homework_checker
        path: checker
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install prerequisites
      run: |
        sudo apt install -y libgtest-dev
        python -m pip install --upgrade pip pipenv
    - name: Run tests
      run: |
        python checker/check_homework.py -v -i homework/homework.yml -o result.md
    - name: Upload result md file
      uses: actions/upload-artifact@v2
      with:
        name: homework_result
        path: results.md

  upload_results_to_wiki:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki
    - name: Download result md file
      uses: actions/download-artifact@v2
      with:
        name: homework_result
    - run: |
        mv results.md wiki/Home.md
        cd wiki
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update results"
        git push